[package]
name = "publicsuffix"
description = "Robust domain name parsing and RFC compliant email address validation"
version = "1.5.5-alpha.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/rushmorem/publicsuffix"
documentation = "https://docs.rs/publicsuffix"
readme = "README.md"
keywords = ["tld", "gtld", "cctld", "domain", "psl"]
authors = ["rushmorem <rushmore@webenchanter.com>"]
edition = "2018"

[features]
default = ["remote_list"]
remote_list = ["native-tls"]

[dependencies]
idna = "0.2"
url = "2.0"

[dependencies.native-tls]
version = "0.2"
optional = true

[dev-dependencies]
criterion = "0.3"
rspec = "=1.0.0-beta.3"

[[bench]]
name = "bench"
harness = false